<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>72f8c699-004c-4979-a664-e94c7b2277ec</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gialora.Data\Gialora.Data.csproj" />
    <ProjectReference Include="..\Gialora.Shared\Gialora.Shared.csproj" />
    <ProjectReference Include="..\Gialora.Application\Gialora.Application.csproj" />
  </ItemGroup>

</Project>
